version: '3'
services:
    client:
        build: .
        # image: graysonchao/credis:latest
        # hack to just stay alive and do nothing
        command: tail -f /var/log/bootstrap.log
    etcd:
        image: appcelerator/etcd
        container_name: credis_etcd
        ports:
            - "2379"
    master:
        build: .
        #image: graysonchao/credis:latest
        command: tail -f /var/log/bootstrap.log
    member:
        build: .
        # image: graysonchao/credis:latest
        command: /bin/bash -c "/run-member.sh -m /credis/build/src -p 6379"
        ports:
        - "6379"
