// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: lease.proto

#include "lease.pb.h"
#include "lease.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace leasepb {

} // namespace leasepb

