// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: record.proto

#include "record.pb.h"
#include "record.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace walpb {

} // namespace walpb

